<?xml version="1.0"?>
<!DOCTYPE PGM [
<!-- Progam scope tree: represents program structure at many source
     code levels.  Because the goal is to represent source code, Ps
     must be children of Fs instead of simply children of a PGM or LM. -->
<!ELEMENT PGM (G|LM|F)+>
<!ATTLIST PGM
	version CDATA #REQUIRED>
  <!-- Groups create arbitrary sets of other elements except PGM. -->
  <!ELEMENT G (G|LM|F|P|L|S)*>
  <!ATTLIST G
	n CDATA #IMPLIED>
  <!-- Runtime load modules for PGM (e.g., DSOs, exe) -->
  <!ELEMENT LM (G|F)*>
  <!ATTLIST LM
	n CDATA #REQUIRED>
  <!-- Files contain procedures and source line info -->
  <!ELEMENT F (G|P|L|S)*>
  <!ATTLIST F
	n CDATA #REQUIRED>
  <!-- Procedures contain source line info 
       n: processed name; ln: link name -->
  <!ELEMENT P (G|L|S)*>
  <!ATTLIST P
	n  CDATA #REQUIRED
	ln CDATA #IMPLIED
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
  <!-- Loops -->
  <!ELEMENT L (G|L|S)*>
  <!ATTLIST L
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
  <!-- Statement/Statement range -->
  <!ELEMENT S EMPTY>
  <!ATTLIST S
	b CDATA #REQUIRED
	e CDATA #IMPLIED
	id CDATA #IMPLIED>
]>
<PGM version="4.0">
   <LM n="example">
      <F n="/home/vuduc2/projects/ROSE/tmp/xml/xerces-c/hpctif/examples/data/01/example.c">
         <P n="main" b="14" e="109">
            <L b="14" e="15">
               <S b="14" e="14"/>
               <S b="15" e="15"/>
            </L>
            <L b="22" e="100">
               <S b="22" e="22"/>
               <L b="25" e="26">
                  <S b="25" e="25"/>
                  <S b="26" e="26"/>
               </L>
               <S b="100" e="100"/>
            </L>
            <L b="42" e="46">
               <S b="42" e="42"/>
               <S b="43" e="43"/>
               <S b="45" e="45"/>
               <S b="46" e="46"/>
            </L>
         </P>
         <P n="mv" b="53" e="64">
            <L b="56" e="62">
               <S b="56" e="56"/>
               <S b="59" e="59"/>
               <L b="61" e="62">
                  <S b="61" e="61"/>
                  <S b="62" e="62"/>
               </L>
            </L>
         </P>
      </F>
   </LM>
</PGM>
