<?xml version="1.0"?>
<!DOCTYPE PROFILE [
<!-- Profile: correlates profiling info with program structure. -->
<!ELEMENT PROFILE (PROFILEHDR, PROFILEPARAMS, PROFILESCOPETREE)>
<!ATTLIST PROFILE
	version CDATA #REQUIRED>
  <!ELEMENT PROFILEHDR (#PCDATA)>
  <!ELEMENT PROFILEPARAMS (TARGET, METRICS)>
    <!ELEMENT TARGET EMPTY>
    <!ATTLIST TARGET
	name CDATA #REQUIRED>
    <!ELEMENT METRICS (METRIC)+>
    <!ELEMENT METRIC EMPTY>
    <!ATTLIST METRIC
	shortName   CDATA #REQUIRED
	nativeName  CDATA #REQUIRED
	period      CDATA #REQUIRED
	units       CDATA #IMPLIED
	displayName CDATA #IMPLIED
	display     (true|false) #IMPLIED>
  <!ELEMENT PROFILESCOPETREE (PGM)*>
    <!-- This is essentially the PGM dtd with M element added. -->
    <!ELEMENT PGM (G|LM|F|M)+>
    <!ATTLIST PGM
	n CDATA #REQUIRED>
    <!-- Groups create arbitrary sets of other elements except PGM. -->
    <!ELEMENT G (G|LM|F|P|L|S|M)*>
    <!ATTLIST G
	n CDATA #IMPLIED>
    <!-- Runtime load modules for PGM (e.g., DSOs, exe) -->
    <!ELEMENT LM (G|F|M)*>
    <!ATTLIST LM
	n CDATA #REQUIRED>
    <!-- Files contain procedures and source line info -->
    <!ELEMENT F (G|P|L|S|M)*>
    <!ATTLIST F
	n CDATA #REQUIRED>
    <!-- Procedures contain source line info 
         n: processed name; ln: link name -->
    <!ELEMENT P (G|L|S|M)*>
    <!ATTLIST P
	n  CDATA #REQUIRED
	ln CDATA #IMPLIED
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
    <!-- Loops -->
    <!ELEMENT L (G|L|S|M)*>
    <!ATTLIST L
	b CDATA #IMPLIED
	e CDATA #IMPLIED>
    <!-- Statement/Statement range -->
    <!ELEMENT S (M)*>
    <!ATTLIST S
	b CDATA #REQUIRED
	e CDATA #IMPLIED
	id CDATA #IMPLIED>
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	n CDATA #REQUIRED
	v CDATA #REQUIRED>
]>
<PROFILE version="3.0">
<PROFILEHDR></PROFILEHDR>
<PROFILEPARAMS>
  <TARGET name="/home/vuduc2/projects/smg2000/data/../preproc-dev/test/smg2000"/>
  <METRICS>
    <METRIC shortName="0" nativeName="PAPI_L2_TCM" displayName="PAPI_L2_TCM" period="32767" units="PAPI events"/>
  </METRICS>
</PROFILEPARAMS>
<PROFILESCOPETREE>
<PGM n="/home/vuduc2/projects/smg2000/data/../preproc-dev/test/smg2000">
  <LM n="/home/vuduc2/projects/smg2000/preproc-dev/test/smg2000">
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/CPP-smg_residual.c">
      <P n="hypre_SMGResidual">
        <S b="216">
          <M n="0" v="32767"/>
        </S>
        <S b="408">
          <M n="0" v="65534"/>
        </S>
        <S b="411">
          <M n="0" v="1.67112e+06"/>
        </S>
        <S b="413">
          <M n="0" v="1.04854e+06"/>
        </S>
        <S b="680">
          <M n="0" v="32767"/>
        </S>
        <S b="684">
          <M n="0" v="294903"/>
        </S>
        <S b="687">
          <M n="0" v="8.87986e+06"/>
        </S>
        <S b="690">
          <M n="0" v="3.5716e+06"/>
        </S>
        <S b="691">
          <M n="0" v="393204"/>
        </S>
        <S b="693">
          <M n="0" v="32767"/>
        </S>
        <S b="716">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/coarsen.c">
      <P n="hypre_StructMapCoarseToFine">
        <S b="58">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/cyclic_reduction.c">
      <P n="hypre_CycRedSetupCoarseOp">
        <S b="367">
          <M n="0" v="98301"/>
        </S>
        <S b="370">
          <M n="0" v="32767"/>
        </S>
        <S b="373">
          <M n="0" v="32767"/>
        </S>
      </P>
      <P n="hypre_CyclicReduction">
        <S b="851">
          <M n="0" v="98301"/>
        </S>
        <S b="853">
          <M n="0" v="458738"/>
        </S>
        <S b="855">
          <M n="0" v="163835"/>
        </S>
        <S b="903">
          <M n="0" v="32767"/>
        </S>
        <S b="908">
          <M n="0" v="131068"/>
        </S>
        <S b="910">
          <M n="0" v="786408"/>
        </S>
        <S b="912">
          <M n="0" v="1.67112e+06"/>
        </S>
        <S b="921">
          <M n="0" v="32767"/>
        </S>
        <S b="996">
          <M n="0" v="196602"/>
        </S>
        <S b="998">
          <M n="0" v="65534"/>
        </S>
        <S b="999">
          <M n="0" v="2.65413e+06"/>
        </S>
        <S b="1000">
          <M n="0" v="884709"/>
        </S>
        <S b="1059">
          <M n="0" v="131068"/>
        </S>
        <S b="1061">
          <M n="0" v="622573"/>
        </S>
        <S b="1128">
          <M n="0" v="98301"/>
        </S>
        <S b="1130">
          <M n="0" v="819175"/>
        </S>
        <S b="1131">
          <M n="0" v="2.62136e+06"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/semi_interp.c">
      <P n="hypre_SemiInterp">
        <S b="220">
          <M n="0" v="32767"/>
        </S>
        <S b="225">
          <M n="0" v="131068"/>
        </S>
        <S b="227">
          <M n="0" v="131068"/>
        </S>
        <S b="229">
          <M n="0" v="262136"/>
        </S>
        <S b="294">
          <M n="0" v="229369"/>
        </S>
        <S b="295">
          <M n="0" v="393204"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/semi_restrict.c">
      <P n="hypre_SemiRestrict">
        <S b="260">
          <M n="0" v="32767"/>
        </S>
        <S b="262">
          <M n="0" v="327670"/>
        </S>
        <S b="263">
          <M n="0" v="786408"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/smg.c">
      <P n="hypre_SMGSetStructVectorConstantValues">
        <S b="413">
          <M n="0" v="32767"/>
        </S>
        <S b="415">
          <M n="0" v="360437"/>
        </S>
        <S b="421">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/smg2_setup_rap.c">
      <P n="hypre_SMG2BuildRAPSym">
        <S b="375">
          <M n="0" v="32767"/>
        </S>
        <S b="385">
          <M n="0" v="32767"/>
        </S>
        <S b="448">
          <M n="0" v="32767"/>
        </S>
        <S b="451">
          <M n="0" v="32767"/>
        </S>
        <S b="452">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/smg3_setup_rap.c">
      <P n="hypre_SMG3BuildRAPSym">
        <S b="608">
          <M n="0" v="32767"/>
        </S>
        <S b="613">
          <M n="0" v="32767"/>
        </S>
        <S b="617">
          <M n="0" v="32767"/>
        </S>
        <S b="654">
          <M n="0" v="32767"/>
        </S>
        <S b="659">
          <M n="0" v="32767"/>
        </S>
        <S b="674">
          <M n="0" v="65534"/>
        </S>
        <S b="681">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_ls/smg_axpy.c">
      <P n="hypre_SMGAxpy">
        <S b="67">
          <M n="0" v="32767"/>
        </S>
        <S b="69">
          <M n="0" v="229369"/>
        </S>
        <S b="71">
          <M n="0" v="163835"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/communication.c">
      <P n="hypre_InitializeCommunication">
        <S b="454">
          <M n="0" v="32767"/>
        </S>
        <S b="456">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/computation.c">
      <P n="hypre_InitializeIndtComputations">
        <S b="376">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/struct_axpy.c">
      <P n="hypre_StructAxpy">
        <S b="69">
          <M n="0" v="327670"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/struct_innerprod.c">
      <P n="hypre_StructInnerProd">
        <S b="87">
          <M n="0" v="32767"/>
        </S>
        <S b="89">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/struct_matrix.c">
      <P n="hypre_StructMatrixInitializeData">
        <S b="357">
          <M n="0" v="65534"/>
        </S>
      </P>
      <P n="hypre_StructMatrixSetBoxValues">
        <S b="554">
          <M n="0" v="65534"/>
        </S>
      </P>
    </F>
    <F n="/home/vuduc2/projects/smg2000/data/../preproc-dev/struct_mv/struct_vector.c">
      <P n="hypre_StructVectorSetBoxValues">
        <S b="345">
          <M n="0" v="32767"/>
        </S>
        <S b="347">
          <M n="0" v="32767"/>
        </S>
      </P>
      <P n="hypre_StructVectorSetConstantValues">
        <S b="576">
          <M n="0" v="131068"/>
        </S>
        <S b="578">
          <M n="0" v="65534"/>
        </S>
      </P>
      <P n="hypre_StructVectorClearGhostValues">
        <S b="643">
          <M n="0" v="32767"/>
        </S>
      </P>
    </F>
  </LM>
  <LM n="/lib/tls/libc-2.3.2.so">
    <F n="&lt;unknown&gt;">
      <P n="__libc_calloc">
        <M n="0" v="32767"/>
      </P>
      <P n="__libc_malloc">
        <M n="0" v="65534"/>
      </P>
    </F>
  </LM>
</PGM>
</PROFILESCOPETREE>
</PROFILE>
